# Generated by Django 3.0.7 on 2021-02-14 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDiri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_depan', models.CharField(max_length=200)),
                ('nama_belakang', models.CharField(max_length=200)),
                ('alamat', models.TextField()),
                ('bio', models.TextField()),
                ('phone', models.CharField(max_length=13)),
                ('kelamin', models.CharField(choices=[('Perempuan', 'Perempuan'), ('Laki_laki', 'Laki_laki')], max_length=255)),
                ('umur', models.IntegerField()),
                ('kota', models.IntegerField()),
                ('pemilik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
